# Generated by Django 6.0.2 on 2026-04-29 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountmembership_role_accountinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinvitation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.account'),
        ),
    ]
