""" Handles rendering of markdown content in templates. The apps LLM prompts direct for responses to be formatted as markdown, and this ensures it is rendered correctly. """
from __future__ import annotations

from django.template import Library
from django.utils.safestring import mark_safe
import markdown


register = Library()

@register.filter
def render_markdown(value: str) -> str:
    """
    Python-Markdown passes through raw HTML, so we need to ensure only trusted content is rendered. In this case we only trust content generated by the LLM or by the application. User-submitted
    HTML is not trusted and should not be rendered.
    """
    return mark_safe(markdown.markdown(value))
