# Generated by Django 6.0.2 on 2026-04-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetype',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
