# Generated by Django 6.0.2 on 2026-04-13 01:39

from django.db import migrations


def seed_demo_source_types(apps, schema_editor):
    SourceType = apps.get_model('sources', 'SourceType')
    demo_types = [
        {'name': 'HubSpot (Demo)', 'is_demo': True},
        {'name': 'Google Analytics (Demo)', 'is_demo': True},
        {'name': 'Customer Database (Demo)', 'is_demo': True},
    ]
    for data in demo_types:
        SourceType.objects.get_or_create(name=data['name'], defaults={'is_demo': True})


def unseed_demo_source_types(apps, schema_editor):
    SourceType = apps.get_model('sources', 'SourceType')
    SourceType.objects.filter(is_demo=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('sources', '0002_sourcetype_is_demo'),
    ]

    operations = [
        migrations.RunPython(seed_demo_source_types, unseed_demo_source_types),
    ]


