# Generated by Django 6.0.2 on 2026-05-18 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountinvitation_account'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('sources', '0003_seed_demo_source_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.account')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='sources.source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
