# Generated by Django 6.0.2 on 2026-05-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_sourceschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='first_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcesynclog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcesynclog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
