# Generated by Django 6.0.2 on 2026-08-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_alter_source_first_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetype',
            name='airbyte_connector_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
