# Generated by Django 6.0.2 on 2026-08-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_seed_stripe_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetype',
            name='config_example',
            field=models.TextField(blank=True),
        ),
    ]
