""" Manages the creation of cross-source insights through a multistep pipeline. The pipeline finds a broad set of potential relationships and then generates insights for the relationships that are
likely to generate the highest quality insights. Requires at least two synced sources to run. """
from __future__ import annotations
import logging

from django.db import transaction

from apps.sources.models import Source
from apps.insights.models import Insight, InsightTarget
from apps.insights.services.provider import get_service
from django.contrib.contenttypes.models import ContentType


logger = logging.getLogger(__name__)


# Each join opportunity has a confidence score that we use to rank them, rank is used to filter to a smaller set of join opportunities.
CONFIDENCE_RANK = {
    'high': 3,
    'medium': 2,
    'low': 1
}
# Always set semantic overlap rank to 0 as we are not currently using it, but stubbed it for future use.
SEMANTIC_OVERLAP_RANK = 0

def _flatten_and_rank_relationships(relationship: dict) -> list[dict]:
    """
    - Receives and flattens a JSON object generated by the cross-source relationship discovery service so that the flattened list can be used downstream in the pipeline.
    - Adds a rank field to each join opportunity and semantic overlap, rank is used to filter to a smaller set of join opportunities.
    - Currently only join opportunities are used, so all semantic overlaps are set to 0 (the lowest possible rank).
    """
    join_opportunities = relationship.get('join_opportunities', [])
    semantic_overlaps = relationship.get('semantic_overlaps', [])
    for jo in join_opportunities:
        jo['_rank'] = CONFIDENCE_RANK.get(jo.get('confidence', '').lower(), 0)
    for so in semantic_overlaps:
        so['_rank'] = SEMANTIC_OVERLAP_RANK
    merged = join_opportunities + semantic_overlaps
    merged.sort(key=lambda item: item['_rank'], reverse=True)
    for item in merged:
        del item['_rank']
    return merged

def run_discovery_for_pair(source_a: Source, source_b: Source, run=None) -> int:
    """
    - For a given pair of sources, runs the cross-source relationship discovery pipeline.
    - The pipeline consists of multiple steps: generating potential relationships, flattening/ranking those relationships before taking the top 5, generating hypotheses for the top 5 relationships, and selecting the top 5 hypotheses.
    - The top 5 use cases are stored, and the function returns the count of stored use cases.
    - Since this service relies on a third-party API, it is resilient to errors or failures. When there is a failure, it is logged and the pipeline continues on to the next relationship pair.
    - The run parameter is not currently used. This is stubbed to be used for a future state where we allow an agent to run the pipeline on its own, currently the pipeline must be invoked by a user.
    """
    service = get_service('anthropic')
    relationship_dict = service.discover_cross_source_relationships(source_a, source_b)
    merged = _flatten_and_rank_relationships(relationship_dict)
    top_5_relationships = merged[:5]
    hypotheses = []
    for relationship in top_5_relationships:
        try:
            hypotheses.extend(service.generate_cross_source_hypotheses(relationship, source_a, source_b))
        except Exception:
            logger.exception("Failed to generate join hypothesis for source pair %s-%s; skipping", source_a, source_b)
            continue
    sorted_hypotheses = sorted(hypotheses, key=lambda h: h.get('specificity_score') or 0.0, reverse=True)
    top_5_hypotheses = sorted_hypotheses[:5]
    created_use_cases = 0
    for hypothesis in top_5_hypotheses:
        try:
            use_case = service.generate_cross_source_use_case(hypothesis, source_a, source_b)
            _store_cross_source_use_case(use_case, source_a, source_b)
            created_use_cases += 1
        except Exception:
            logger.exception("Failed to generate use case for hypothesis %s; skipping", hypothesis.get('title') or 'unknown')
            continue
    return created_use_cases

def _store_cross_source_use_case(use_case_data: dict, source_a: Source, source_b: Source) -> Insight:
    """
    - Stores a cross-source use case in the database; since this applies to two sources, we do this atomically to ensure insight is associated to both sources.
    - Receives a JSON object generated by the cross-source use case generation service.
    """
    account = source_a.account
    with transaction.atomic():
        insight = Insight.objects.create(
            account=account,
            text=use_case_data['title'],
            insight_type='cross_source_use_case',
            status='pending_review',
            insight_prompt=None,
            structured_data=use_case_data,
        )
        source_ct = ContentType.objects.get_for_model(Source)
        InsightTarget.objects.create(account=account, insight=insight, content_type=source_ct, object_id=source_a.pk)
        InsightTarget.objects.create(account=account, insight=insight, content_type=source_ct, object_id=source_b.pk)
    return insight
