# Generated by Django 6.0.2 on 2026-04-08 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('column_stats', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.account')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
