# Generated by Django 6.0.2 on 2026-03-27 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('insights', '0002_insightprompt_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insighttarget',
            name='target',
        ),
        migrations.AddField(
            model_name='insighttarget',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insighttarget',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
