# Generated by Django 6.0.2 on 2026-04-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_remove_insighttarget_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('ai', 'AI Generated'), ('manual', 'Manual'), ('use_case_suggestion', 'Use Case Suggestion')], max_length=255),
        ),
    ]
