# Generated by Django 6.0.2 on 2026-04-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_insight_structured_data_alter_insight_insight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='rating',
            field=models.CharField(choices=[('none', 'None'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
