# Generated by Django 6.0.2 on 2026-05-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_insight_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed'), ('archived', 'Archived'), ('deleted', 'Deleted')], max_length=255),
        ),
    ]
