# Generated by Django 6.0.2 on 2026-05-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0006_alter_insight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('ai', 'AI Generated'), ('table_description', 'Table Description'), ('source_overview', 'Source Overview'), ('use_case_suggestion', 'Use Case Suggestion'), ('manual', 'Manual')], max_length=255),
        ),
    ]
