# Generated by Django 6.0.2 on 2026-05-18 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0008_retype_ai_insights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insights.insightprompt'),
        ),
    ]
