# Generated by Django 6.0.2 on 2026-06-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0009_alter_insight_insight_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('ai', 'AI Generated'), ('table_description', 'Table Description'), ('source_overview', 'Source Overview'), ('use_case_suggestion', 'Use Case Suggestion'), ('cross_source_use_case', 'Cross Source Use Case'), ('manual', 'Manual')], max_length=255),
        ),
        migrations.AlterField(
            model_name='insight',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('dismissed', 'Dismissed'), ('failed', 'Failed'), ('archived', 'Archived'), ('deleted', 'Deleted')], max_length=255),
        ),
    ]
